source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "7.0.2.3"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "5.6.2"

# PostgreSQL
gem "pg"

# GraphQL
gem "graphql"

# Use Redis adapter to run Action Cable in production
gem "redis"

# Redis backed store for Rack::Cache, an HTTP cache.
gem "redis-rack-cache"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

# Environment
gem "dotenv-rails"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Devise
gem "devise"

# Devise token authentication
gem "devise-token_authenticatable"

# A Rails plugin to add soft delete
gem "acts_as_paranoid"

# Track changes to your models, for auditing or versioning
gem "paper_trail"

group :development do
  # Use the GraphiQL IDE for GraphQL with Ruby on Rails
  gem "graphiql-rails"
end

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "pry"

  # faker
  gem "faker"

  # factory_bot is a fixtures replacement
  gem "factory_bot_rails"

  # rspec testing framework
  %w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
    gem lib, git: "https://github.com/rspec/#{lib}.git", branch: "main"
  end
end
